media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: image
        label: Image
        type: media
      - name: body
        label: Body
        type: rich-text