media:
  input: src/assets
  output: /assets
content:
  - name: blog
    label: Blog
    type: collection
    path: 'src/blog'
    view:
      fields: [ title, published, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: author
        label: Author
        type: string
      - name: postDate
        label: Date
        type: date
      - name: image
        label: Image
        type: image
      - name: imageAlt
        label: Image Caption
        type: string
      - name: description
        label: Description
        type: string
      - name: published
        label: Published
        type: boolean
      - name: tags
        label: Tags
        type: select
        options:
          values: { value: ["post", "featured"], label: Featured }
      - name: body
        label: Body
        type: rich-text
  - name: site
    label: Site settings
    path: src/_data/site.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)